fastq1: "/gpfs1/projects/Pools/RD_projects/Influenza_p1864_PQ00652_variant_calling/final_fastq/deduplicated/{sample}/{sample}.final.1.fq.bz2"
fastq2: "/gpfs1/projects/Pools/RD_projects/Influenza_p1864_PQ00652_variant_calling/final_fastq/deduplicated/{sample}/{sample}.final.2.fq.bz2"
inputDir: "/gpfs1/projects/Pools/RD_projects/Influenza_p1864_PQ00652_variant_calling/final_fastq/deduplicated"
outputDir: "/gpfs1/projects/Pools/RD_projects/Influenza_p1864_PQ00652_variant_calling/output/{sample}"
samplefile: "refgenome_mapping"
refGenome: "/gpfs1/projects/Pools/RD_projects/Influenza_p1864_PQ00652_variant_calling/references"
snpEffconfig: "snpEff.config"

#mpileup options: http://www.htslib.org/doc/samtools-mpileup.html
#--fasta-ref set in SnakeFile
mpileupParams: "-aa --count-orphans --no-BAQ --max-depth 500000 -Q 0" 

#ivar options: https://andersen-lab.github.io/ivar/html/manualpage.html 
#-r set in SnakeFile
ivarParams: "-q 20 -t 0.03"

#ivar_variants_to_vcf.py options 
# --pass_only: Only output variants that PASS all filters.
# --allele_freq_thresh: Only output variants where allele frequency greater than this number (default: 0). 
convertToVcfParams: "--pass_only --allele_freq_thresh 0"
